AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-serverless-app
  Sample SAM Template for my-serverless-app

Globals:
  Function:
    Timeout: 30

Parameters:
  PokemonApi:
    Type: String
    Description: API url for retrieving pokemon data
    Default: https://pokeapi.co/api/v2

Resources:
  PokemonFibFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Environment:
        Variables:
          POKEMON_API: !Ref PokemonApi
      Handler: src.main.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /pokemon-fib/{id}
            Method: get

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PokemonFibApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  PokemonFibFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  PokemonFibunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
